# Lesson 1

## softmax

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
scores = np.array([1., 2., 3.])

def softmax(x):
    exps = np.exp(x)
    expsum = np.sum(exps, axis=0)
    return exps / expsum

softmax(scores)

array([ 0.09003057,  0.24472847,  0.66524096])

In [3]:
mul = np.linspace(1., 10., 10)
mul

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [4]:
scores[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

In [5]:
mul[np.newaxis, :]

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [6]:
softmax(mul_scores)

NameError: name 'mul_scores' is not defined

In [ ]:
mul_scores = scores[:, np.newaxis] * mul[np.newaxis, :]
mul_scores

In [ ]:
plt.plot(mul_scores[0], softmax(mul_scores).T)
plt.show()

# probabilities approaches 0 and 1

In [ ]:
div = np.linspace(1., 10., 10)
div

In [ ]:
div_scores = scores[:, np.newaxis] / div[np.newaxis, :]
div_scores

In [ ]:
plt.plot(div_scores[0], softmax(div_scores).T)
plt.show()

# approaches uniform distribution

### Numerical stability

In [ ]:
a = 1000000000
for i in range(1, 1000001):
    a = a + 0.000001
    
a = a - 1000000000
print(a)

In [7]:
softmax([0, 0, 0])

array([ 0.33333333,  0.33333333,  0.33333333])