# Lesson 1

## softmax

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
scores = np.array([1., 2., 3.])

def softmax(x):
    exps = np.exp(x)
    expsum = np.sum(exps, axis=0)
    return exps / expsum

softmax(scores)

array([ 0.09003057,  0.24472847,  0.66524096])

In [3]:
mul = np.linspace(1., 10., 10)
mul

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [4]:
scores[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

In [5]:
mul[np.newaxis, :]

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [6]:
softmax(mul_scores)

NameError: name 'mul_scores' is not defined

In [ ]:
mul_scores = scores[:, np.newaxis] * mul[np.newaxis, :]
mul_scores

In [ ]:
plt.plot(mul_scores[0], softmax(mul_scores).T)
plt.show()

# probabilities approaches 0 and 1

In [ ]:
div = np.linspace(1., 10., 10)
div

In [ ]:
div_scores = scores[:, np.newaxis] / div[np.newaxis, :]
div_scores

In [ ]:
plt.plot(div_scores[0], softmax(div_scores).T)
plt.show()

# approaches uniform distribution

### Numerical stability

In [ ]:
a = 1000000000
for i in range(1, 1000001):
    a = a + 0.000001
    
a = a - 1000000000
print(a)

In [7]:
softmax([0, 0, 0])

array([ 0.33333333,  0.33333333,  0.33333333])

### Import tensorflow graph

In [1]:
import tensorflow as tf
from six.moves import cPickle as pickle

In [2]:
with open('train.pickle', "rb") as f_train:
    train_dataset, train_labels = pickle.load(f_train)
    
    graph = tf.get_default_graph()
    
    with tf.Session(graph=graph) as session:
        
        loader = tf.train.import_meta_graph('svhn.meta')
        loader.restore(session, tf.train.latest_checkpoint('./'))
        
        tf_data = graph.get_tensor_by_name('data:0')
        keep_prob = graph.get_tensor_by_name('keep_prob:0')
        prediction = graph.get_tensor_by_name('prediction:0')
        
        feed_dict = {
            tf_data: train_dataset[0:1, :, :, :],
            keep_prob: 1.0
        }
        
        p = prediction.eval(feed_dict)
        print(p)

INFO:tensorflow:Restoring parameters from ./svhn
[[  4.48429666e-04   7.44634569e-01   7.95392618e-02   3.67643777e-03
    1.35538727e-01   1.79281051e-05   7.03091151e-04   1.85851578e-03
    2.99448632e-02   3.63584165e-03   2.25045483e-06]
 [  3.18712108e-02   4.31372505e-03   4.62858260e-01   2.88116396e-03
    2.20801741e-01   1.99659402e-03   4.79037687e-03   2.52970727e-04
    2.99525820e-02   2.40254939e-01   2.64849004e-05]
 [  2.10791118e-02   6.10287301e-03   1.06635848e-02   1.01347920e-02
    1.30682811e-01   9.85813560e-04   1.69320416e-03   3.82522051e-03
    8.23673792e-03   1.84603520e-02   7.88135529e-01]
 [  8.86473063e-05   2.40588888e-05   2.82053894e-04   9.37953766e-04
    5.93061995e-05   7.94850988e-04   1.28658095e-04   9.16504869e-05
    1.09198620e-04   1.27588835e-04   9.97356057e-01]
 [  1.23707027e-08   2.59154334e-08   3.66853385e-07   2.20430502e-06
    2.68238682e-06   4.33506898e-07   1.22027586e-06   1.03348867e-08
    1.91046240e-07   1.97015697e-06

In [2]:
''.append('0')

AttributeError: 'str' object has no attribute 'append'